### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by heberq** [tngoman/HostingBilling#1]
Hello,
I've been trying to use billing hosting for some time, but I'm having a problem that it's not sending data from the server to the client.

Looking at the demo, I noticed that it remains the same. Within well server settings put the dns ns1, ns2 and others.

However, this data is not sent to the clients.

Could you check or make a tutorial about it?

graciously
Heber Queiroz

**Comment by tngoman** [comment]
Hi, by client you mean the customer?
Not sure I understand but it sounds like you're saying changes are not being saved?

**Comment by heberq** [comment]
As can be seen from the images, in the form for registering the server I have the hostname and dns of the server.
But in the hosting account email template, I have no way to enter these details. The customer cannot point domain and cannot access his account due to the lack of this data.

![server](https://user-images.githubusercontent.com/2167737/157292278-121a5446-3c73-47e2-93ba-d23ba233a398.png)
![mail](https://user-images.githubusercontent.com/2167737/157292322-cc1f71ae-87ed-4267-a4a0-d4ded1bed333.png)

**Comment by tngoman** [comment]
Regarding the cPanel link. You want your customers to reach their cPanel through your website and not their own?
Since their own would be {DOMAIN}:8083 or {DOMAIN}/cpanel

Regarding DNS you are saying in the email you want to show your default nameservers?

You also want a variable for your hostname and not the customer's domain because at that time it may not have propagated yet?

**Comment by heberq** [comment]
That's right, because they have this issue of the domain not being propagated and another thing, my dns are not appearing anywhere so that customers can put it in their domain.

**Comment by tngoman** [comment]
Will add the hostname variable.
Will need to think about the nameservers a bit because you may have multiple servers. 
The reason to enter nameservers when adding a server is so that the domain registration process knows where the cPanel account is sitting.

**Comment by heberq** [comment]
I agree with you, but pulling the hostname from the server register and dns, clients will be able to access the server panel without any problem.

**Comment by tngoman** [comment]
Server URL and Nameserver variables have been added. 

See Hosting Account email template in live demo.

https://github.com/tngoman/HostingBilling/blob/main/application/helpers/app_helper.php

https://github.com/tngoman/HostingBilling/blob/main/application/models/Order.php
