### ISSUE TITLE
How to deactivate the website

### ISSUE THREAD

**Issue by heberq** [tngoman/HostingBilling#10]
Where do I have to configure to remove the site and leave only the active panel for the client to have access to?
I would like to do this on mine, as I saw that several times you put the FAQ or the Knowledge Base as Home.
Please, if you can make a tutorial, I will be grateful.

Thank You
Heber Queiroz

**Comment by tngoman** [comment]
Its not possible to remove the website but you can change the default home page in config.

In application/config/routes.php

You can change the default controller on line 41

From:
$route['default_controller'] = 'home';

To:
$route['default_controller'] = 'knowledge';

This will make the knowledge base the home page.
