### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by foxpcteam** [tngoman/HostingBilling#12]
Hi,

where is the Installation guide?

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.

**Comment by tngoman** [comment]
Hi, there's an installer that starts automatically. Not sure if you  need assistance with installing or if the issue is that you couldn't see an installation guide.
