### ISSUE TITLE
Changes are not applied

### ISSUE THREAD

**Issue by servidorhn** [tngoman/HostingBilling#2]
Greetings, after installing the script I have found these problems, in the products and services section when adding a product and deactivating the option to require domain this change is not saved and always remains active.

![Screenshot_1](https://user-images.githubusercontent.com/71868222/156507838-4c45b461-0c5b-4431-9deb-daa19e7352a9.jpg)

**Comment by tngoman** [comment]
Hi, there was a missing line in: \application\modules\items\views\modal\edit_service.php

Please see: https://github.com/tngoman/HostingBilling/commit/053617cdb4e88b10642c40da68ca05309c9c35e6

You can copy the line that has +

And paste it in the same location in your code.
