### ISSUE TITLE
Cyberpanel

### ISSUE THREAD

**Issue by lahorenc** [tngoman/HostingBilling#3]
Hi
nice job!
1. Can you edit captcha on you web site, I can't select right item.
2. Can you provide some additional instruction for connection to Cyberpanel api? Where I can find api key on Cyber panel? What credentials I need for using api?

Everything else is done great, a lot of effort and time.

**Comment by tngoman** [comment]
Hi,

Captcha has been edited.
I believe Cyberpanel uses a username and password instead of API keys.
Detailed API info is available here: https://cyberpanel.docs.apiary.io/#reference/server/login-as-user/login-as-user
