### ISSUE TITLE
Register domain without domain registrars

### ISSUE THREAD

**Issue by heberq** [tngoman/HostingBilling#9]
First, thanks for resolving the DNS issue.
I would like to know, as I live in Brazil, the system that registers domains is Registro.br.
But if it is for me to have a license like the resellerclub, the value is very high.
I would like to know, in Hosting Billing can I sell domains without a registrar, just like boxbilling?

**Comment by tngoman** [comment]
You can sell domains without a registrar but you want to make sure the domains is actually available and for that don't use the basic checker. Use the whoisxml api. It's included in Hosting Billing as a free plugin.
They give you 500 free checks every month. You can top up if needed.
